
server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

   
    location /api/vitrine  { proxy_pass http://vitrine-service:8080; }
    location /api/produtos { proxy_pass http://catalogo-service:8081; }
    location /api/pedido   { proxy_pass http://pedido-service:8082; }

   
    location / {
        try_files $uri $uri/ /index.html;
    }
}
