services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:7.0.14
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

  pedido-service:
    build: ./pedido-service
    environment:
      MONGO_URL: ${MONGO_URL}
      CATALOGO_URL: ${CATALOGO_URL}
    ports:
      - "8082:8082"
    depends_on:
      mongodb:
        condition: service_healthy
      catalogo-service:
        condition: service_started

  catalogo-service:
    build: ./catalogo-service
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  vitrine-service:
    build: ./vitrine-service
    environment:
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      CATALOGO_URL: ${CATALOGO_URL}
    ports:
      - "8080:8080"
    depends_on:
      - catalogo-service

  prometheus:
    image: prom/prometheus:v3.4.1
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - vitrine-service

  grafana:
    image: grafana/grafana:12.0.2
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./observability/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./observability/grafana-dashboard-provider.yml:/etc/grafana/provisioning/dashboards/provider.yml
      - ./observability/grafana-dashboard.json:/var/lib/grafana/dashboards/cacheiro.json
    ports:
      - "3000:3000"
    depends_on:
      - prometheus