global:
  scrape_interval: 15s

scrape_configs:
  - job_name: vitrine-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["vitrine-service:8080"]

  - job_name: pedidos-service
    metrics_path: /metrics
    static_configs:
    - targets: [ "pedidos-service:8082" ]
