server:
  port: 8081

spring:
  application:
    name: catalogo-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogo
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

catalogo:
  latencia-simulada-ms: 300