server:
  port: 8080

spring:
  application:
    name: vitrine-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

vitrine:
  catalogo-url: ${CATALOGO_URL:http://localhost:8081}
  cache:
    ttl-produto: 45s
    ttl-lista: 20s
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
